live_config_reload = true

[colors.bright]
black = "0x3b3b3b"
blue = "0x4f9cfe"
cyan = "0x56d8c9"
green = "0x83c746"
magenta = "0xff81ca"
red = "0xff5e56"
white = "0xdedede"
yellow = "0xefc541"

[colors.normal]
black = "0x252525"
blue = "0x368aeb"
cyan = "0x3fc5b7"
green = "0x70b433"
magenta = "0xeb6eb7"
red = "0xed4a46"
white = "0x777777"
yellow = "0xdbb32d"

[colors.primary]
background = "0x181818"
foreground = "0xb9b9b9"

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 8.5

[font.bold]
family = "Berkeley Mono"
style = "Bold"

[font.bold_italic]
family = "Berkeley Mono"
style = "Bold Italic"

[font.italic]
family = "Berkeley Mono"
style = "Italic"

[font.normal]
family = "Berkeley Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
dynamic_title = true

[window.dimensions]
columns = 238
lines = 61

[window.padding]
x = 10
y = 10
